class AllPIList{

  late List<List<String>> allPara = <List<String>>[
    imaPara1,
    imaPara2,
    imaPara3,
    imaPara4,
    imaPara5,
    imaPara6,
    imaPara7,
    imaPara8,
    imaPara9,
    imaPara10,
    imaPara11,
    imaPara12,
    imaPara13,
    imaPara14,
    imaPara15,
    imaPara16,
    imaPara17,
    imaPara18,
    imaPara19,
    imaPara20,
    imaPara21,
    imaPara22,
    imaPara23,
    imaPara24,
    imaPara25,
    imaPara26,
    imaPara27,
    imaPara28,
    imaPara29,
    imaPara30
  ];
  List<String> paraS=[
    "PARA - 01",
    "PARA - 02",
    "PARA - 03",
    "PARA - 04",
    "PARA - 05",
    "PARA - 06",
    "PARA - 07",
    "PARA - 08",
    "PARA - 09",
    "PARA - 10",
    "PARA - 11",
    "PARA - 12",
    "PARA - 13",
    "PARA - 14",
    "PARA - 15",
    "PARA - 16",
    "PARA - 17",
    "PARA - 18",
    "PARA - 19",
    "PARA - 20",
    "PARA - 21",
    "PARA - 22",
    "PARA - 23",
    "PARA - 24",
    "PARA - 25",
    "PARA - 26",
    "PARA - 27",
    "PARA - 28",
    "PARA - 29",
    "PARA - 30"
  ];
  List<String> paraName=[
    "Alif La'm Meem",
    "Sayaqoolu",
    "Tilkal Rusull",
    "Lan Tana Loo",
    "Wal Mohsanat",
    "La Yuhibbullah",
    "Wa Iza Samiu",
    "Wa Lau Annana",
    "Qalal Malao",
    "Wa A'lamu",
    "Yatazeroon",
    "Wa Mamin Da'abat",
    "Wa Ma Ubrioo",
    "Rubama",
    "Subhanallazi",
    "Qal Alam",
    "Aqtarabo",
    "Qadd Aflaha",
    "Wa Qalallazina",
    "A'man Khalaq",
    "Utlu Ma Oohi",
    "Wa Manyaqnut",
    "Wa Mali",
    "Faman Azlam",
    "Elahe Yuruddo",
    "Ha'a Meem",
    "Qala Fama Khatbukum",
    "Qadd Sami Allah",
    "Tabarakallazi",
    "Amma Yatasa'aloon"
  ];


  List<String> imaPara1 = [
    "assets/images/1.png",
    "assets/images/2.png",
    "assets/images/3.png",
    "assets/images/4.png",
    "assets/images/5.png",
    "assets/images/6.png",
    "assets/images/7.png",
    "assets/images/8.png",
    "assets/images/9.png",
    "assets/images/10.png",
    "assets/images/11.png",
    "assets/images/12.png",
    "assets/images/13.png",
    "assets/images/14.png",
    "assets/images/15.png",
    "assets/images/16.png",
    "assets/images/17.png",
    "assets/images/18.png",
    "assets/images/19.png",
    "assets/images/20.png",
    "assets/images/21.png"
  ];

  List<String> imaPara2 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara3 = [
    "assets/images/42.png",
    "assets/images/43.png",
    "assets/images/44.png",
    "assets/images/45.png",
    "assets/images/46.png",
    "assets/images/47.png",
    "assets/images/48.png",
    "assets/images/49.png",
    "assets/images/50.png",
    "assets/images/51.png",
    "assets/images/52.png",
    "assets/images/53.png",
    "assets/images/54.png",
    "assets/images/55.png",
    "assets/images/56.png",
    "assets/images/57.png",
    "assets/images/58.png",
    "assets/images/59.png",
    "assets/images/60.png",
    "assets/images/61.png"
  ];
  List<String> imaPara4 = [
    "assets/images/62.png",
    "assets/images/63.png",
    "assets/images/64.png",
    "assets/images/65.png",
    "assets/images/66.png",
    "assets/images/67.png",
    "assets/images/68.png",
    "assets/images/69.png",
    "assets/images/70.png",
    "assets/images/71.png",
    "assets/images/72.png",
    "assets/images/73.png",
    "assets/images/74.png",
    "assets/images/75.png",
    "assets/images/76.png",
    "assets/images/77.png",
    "assets/images/78.png",
    "assets/images/79.png",
    "assets/images/80.png",
    "assets/images/81.png"
  ];
  List<String> imaPara5 = [
    "assets/images/82.png",
    "assets/images/83.png",
    "assets/images/84.png",
    "assets/images/85.png",
    "assets/images/86.png",
    "assets/images/87.png",
    "assets/images/88.png",
    "assets/images/89.png",
    "assets/images/90.png",
    "assets/images/91.png",
    "assets/images/92.png",
    "assets/images/93.png",
    "assets/images/94.png",
    "assets/images/95.png",
    "assets/images/96.png",
    "assets/images/97.png",
    "assets/images/98.png",
    "assets/images/99.png",
    "assets/images/100.png",
    "assets/images/101.png"
  ];
  List<String> imaPara6 = [
    "assets/images/102.png",
    "assets/images/103.png",
    "assets/images/104.png",
    "assets/images/105.png",
    "assets/images/106.png",
    "assets/images/107.png",
    "assets/images/108.png",
    "assets/images/109.png",
    "assets/images/110.png",
    "assets/images/111.png",
    "assets/images/112.png",
    "assets/images/113.png",
    "assets/images/114.png",
    "assets/images/115.png",
    "assets/images/116.png",
    "assets/images/117.png",
    "assets/images/118.png",
    "assets/images/119.png",
    "assets/images/120.png",
    "assets/images/121.png"
  ];
  List<String> imaPara7 = [
    "assets/images/122.png",
    "assets/images/123.png",
    "assets/images/124.png",
    "assets/images/125.png",
    "assets/images/126.png",
    "assets/images/127.png",
    "assets/images/128.png",
    "assets/images/129.png",
    "assets/images/130.png",
    "assets/images/131.png",
    "assets/images/132.png",
    "assets/images/133.png",
    "assets/images/134.png",
    "assets/images/135.png",
    "assets/images/136.png",
    "assets/images/137.png",
    "assets/images/138.png",
    "assets/images/139.png",
    "assets/images/140.png",
    "assets/images/141.png"
  ];
  List<String> imaPara8 = [
    "assets/images/142.png",
    "assets/images/143.png",
    "assets/images/144.png",
    "assets/images/145.png",
    "assets/images/146.png",
    "assets/images/147.png",
    "assets/images/148.png",
    "assets/images/149.png",
    "assets/images/150.png",
    "assets/images/151.png",
    "assets/images/152.png",
    "assets/images/153.png",
    "assets/images/154.png",
    "assets/images/155.png",
    "assets/images/156.png",
    "assets/images/157.png",
    "assets/images/158.png",
    "assets/images/159.png",
    "assets/images/150.png",
    "assets/images/151.png"
  ];
  List<String> imaPara9 = [
    "assets/images/152.png",
    "assets/images/153.png",
    "assets/images/154.png",
    "assets/images/155.png",
    "assets/images/156.png",
    "assets/images/157.png",
    "assets/images/158.png",
    "assets/images/159.png",
    "assets/images/160.png",
    "assets/images/161.png",
    "assets/images/162.png",
    "assets/images/163.png",
    "assets/images/164.png",
    "assets/images/165.png",
    "assets/images/166.png",
    "assets/images/167.png",
    "assets/images/168.png",
    "assets/images/169.png",
    "assets/images/170.png",
    "assets/images/171.png"
  ];
  List<String> imaPara10 = [
    "assets/images/172.png",
    "assets/images/173.png",
    "assets/images/174.png",
    "assets/images/175.png",
    "assets/images/176.png",
    "assets/images/177.png",
    "assets/images/178.png",
    "assets/images/179.png",
    "assets/images/180.png",
    "assets/images/181.png",
    "assets/images/182.png",
    "assets/images/183.png",
    "assets/images/184.png",
    "assets/images/185.png",
    "assets/images/186.png",
    "assets/images/187.png",
    "assets/images/188.png",
    "assets/images/189.png",
    "assets/images/190.png",
    "assets/images/191.png"
  ];
  List<String> imaPara11 = [
    "assets/images/192.png",
    "assets/images/193.png",
    "assets/images/194.png",
    "assets/images/195.png",
    "assets/images/196.png",
    "assets/images/197.png",
    "assets/images/198.png",
    "assets/images/199.png",
    "assets/images/200.png",
    "assets/images/201.png",
    "assets/images/202.png",
    "assets/images/203.png",
    "assets/images/204.png",
    "assets/images/205.png",
    "assets/images/206.png",
    "assets/images/207.png",
    "assets/images/208.png",
    "assets/images/209.png",
    "assets/images/210.png",
    "assets/images/211.png"
  ];
  List<String> imaPara12 = [
    "assets/images/212.png",
    "assets/images/213.png",
    "assets/images/214.png",
    "assets/images/215.png",
    "assets/images/216.png",
    "assets/images/217.png",
    "assets/images/218.png",
    "assets/images/219.png",
    "assets/images/220.png",
    "assets/images/221.png",
    "assets/images/222.png",
    "assets/images/223.png",
    "assets/images/224.png",
    "assets/images/225.png",
    "assets/images/226.png",
    "assets/images/227.png",
    "assets/images/228.png",
    "assets/images/229.png",
    "assets/images/230.png",
    "assets/images/231.png"
  ];
  List<String> imaPara13 = [
    "assets/images/232.png",
    "assets/images/233.png",
    "assets/images/234.png",
    "assets/images/235.png",
    "assets/images/236.png",
    "assets/images/237.png",
    "assets/images/238.png",
    "assets/images/239.png",
    "assets/images/240.png",
    "assets/images/241.png",
    "assets/images/242.png",
    "assets/images/243.png",
    "assets/images/244.png",
    "assets/images/245.png",
    "assets/images/246.png",
    "assets/images/247.png",
    "assets/images/248.png",
    "assets/images/249.png",
    "assets/images/250.png",
    "assets/images/251.png"
  ];
  List<String> imaPara14 = [
    "assets/images/252.png",
    "assets/images/253.png",
    "assets/images/254.png",
    "assets/images/255.png",
    "assets/images/256.png",
    "assets/images/257.png",
    "assets/images/258.png",
    "assets/images/259.png",
    "assets/images/260.png",
    "assets/images/261.png",
    "assets/images/262.png",
    "assets/images/263.png",
    "assets/images/264.png",
    "assets/images/265.png",
    "assets/images/266.png",
    "assets/images/267.png",
    "assets/images/268.png",
    "assets/images/269.png",
    "assets/images/270.png",
    "assets/images/271.png"
  ];
  List<String> imaPara15 = [
    "assets/images/272.png",
    "assets/images/273.png",
    "assets/images/274.png",
    "assets/images/275.png",
    "assets/images/276.png",
    "assets/images/277.png",
    "assets/images/278.png",
    "assets/images/279.png",
    "assets/images/280.png",
    "assets/images/281.png",
    "assets/images/282.png",
    "assets/images/283.png",
    "assets/images/284.png",
    "assets/images/285.png",
    "assets/images/286.png",
    "assets/images/287.png",
    "assets/images/288.png",
    "assets/images/289.png",
    "assets/images/290.png",
    "assets/images/291.png"
  ];
  List<String> imaPara16 = [
    "assets/images/1.png",
    "assets/images/2.png",
    "assets/images/3.png",
    "assets/images/4.png",
    "assets/images/5.png",
    "assets/images/6.png",
    "assets/images/7.png",
    "assets/images/8.png",
    "assets/images/9.png",
    "assets/images/10.png",
    "assets/images/11.png",
    "assets/images/12.png",
    "assets/images/13.png",
    "assets/images/14.png",
    "assets/images/15.png",
    "assets/images/16.png",
    "assets/images/17.png",
    "assets/images/18.png",
    "assets/images/19.png",
    "assets/images/20.png",
    "assets/images/21.png"
  ];

  List<String> imaPara17 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara18 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara19 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara20 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara21 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara22 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara23 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara24 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara25 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara26 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara27 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara28 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara29 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
  List<String> imaPara30 = [
    "assets/images/22.png",
    "assets/images/23.png",
    "assets/images/24.png",
    "assets/images/25.png",
    "assets/images/26.png",
    "assets/images/27.png",
    "assets/images/28.png",
    "assets/images/29.png",
    "assets/images/30.png",
    "assets/images/31.png",
    "assets/images/32.png",
    "assets/images/33.png",
    "assets/images/34.png",
    "assets/images/35.png",
    "assets/images/36.png",
    "assets/images/37.png",
    "assets/images/38.png",
    "assets/images/39.png",
    "assets/images/40.png",
    "assets/images/41.png"
  ];
}